[package]
name = "behave"
version = "0.1.0"
edition = "2021"

[lib]
path = "lib.rs"

[dependencies]
capnp = "0.18"
iceoryx2 = "0.7"
anyhow = "1"
log = "0.4"
env_logger = "0.11"
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
tokio = { version = "1", features = ["full"] }
indexmap = { version = "2.13.0", features = ["serde"] }

[build-dependencies]
capnpc = "0.18"
glob = "0.3"

# ── Node binaries ───────────────────────────────────────────────

[[bin]]
name = "node-sense-mock"
path = "robot/nodes/sense_mock/main.rs"

[[bin]]
name = "node-sense-sim"
path = "robot/nodes/sense_sim/main.rs"

[[bin]]
name = "node-sense-irl"
path = "robot/nodes/sense_irl/main.rs"

[[bin]]
name = "node-control-sim"
path = "robot/nodes/control_sim/main.rs"

[[bin]]
name = "node-control-mock"
path = "robot/nodes/control_mock/main.rs"

[[bin]]
name = "node-control-irl"
path = "robot/nodes/control_irl/main.rs"

[[bin]]
name = "node-behave"
path = "robot/nodes/behave/main.rs"

[[bin]]
name = "node-communicate"
path = "robot/nodes/communicate/main.rs"

[[bin]]
name = "node-gcs-mock"
path = "robot/nodes/gcs_mock/main.rs"

# ── Runmodes ────────────────────────────────────────────────────

[[bin]]
name = "runmode"
path = "robot/main.rs"
