syntax = "proto3";

package behave.v1;

message Position {
  float latitude = 1;
  float longitude = 2;
  float altitude = 3;
}

message Orientation {
  float yaw = 1;
  float pitch = 2;
  float roll = 3;
}

message Pose {
  Position position = 1;
  Orientation orientation = 2;
}

message Polygon {
  repeated Position positions = 1;
}

message PolygonPrism {
  Polygon polygon = 1;
  float floor = 2;
  float ceiling = 3;
} 

enum GeofenceType {
  GEOFENCE_TYPE_UNSPECIFIED = 0;
  GEOFENCE_TYPE_KEEP_OUT = 1;
  GEOFENCE_TYPE_KEEP_IN = 2;
}

message Geofence {
  GeofenceType type = 1;
  PolygonPrism polygon_prism = 2;
}

message Site {
  repeated Geofence geofences = 1;
  GlobalGraph global_graph = 2;
}

message GlobalGraphNode {
  Pose pose = 1;
}

message GlobalGraphEdge {
  uint32 from = 1;
  uint32 to = 2;
}

message GlobalGraph {
  repeated GlobalGraphNode nodes = 1;
  repeated GlobalGraphEdge edges = 2;
}
