//! Foxglove bridge node -- serves iceoryx2 topics to Foxglove via WebSocket.
//!
//! Subscribes to `behave/ActionRun` and forwards the raw protobuf bytes
//! to connected Foxglove clients. The protobuf FileDescriptorSet is
//! embedded at compile time so Foxglove can decode the messages natively.

use std::time::Duration;

use anyhow::Result;
use iceoryx2::prelude::*;
use log::{info, warn};

use behave::topics;

/// Protobuf FileDescriptorSet generated by prost-build from action.proto.
/// Contains all message types needed to decode ActionRun.
const ACTION_DESCRIPTOR: &[u8] =
    include_bytes!(concat!(env!("OUT_DIR"), "/action_descriptor.bin"));

pub fn run() -> Result<()> {
    behave::logging::init("Foxglove");
    info!("starting");

    // ── Foxglove WebSocket server ─────────────────────────────
    let server = foxglove::WebSocketServer::new()
        .name("behave")
        .bind("0.0.0.0", 8765)
        .start_blocking()
        .map_err(|e| anyhow::anyhow!("failed to start foxglove server: {e}"))?;
    info!("WebSocket server listening on 0.0.0.0:8765");

    // ── Foxglove channel for ActionRun ────────────────────────
    let schema = foxglove::Schema::new(
        "behave.actions.ActionRun",
        "protobuf",
        ACTION_DESCRIPTOR,
    );
    let channel = foxglove::ChannelBuilder::new("/behave/ActionRun")
        .message_encoding("protobuf")
        .schema(schema)
        .build_raw()
        .map_err(|e| anyhow::anyhow!("failed to create channel: {e}"))?;
    info!("channel /behave/ActionRun ready");

    // ── iceoryx2 subscriptions ────────────────────────────────
    let node = NodeBuilder::new().create::<iceoryx2::prelude::ipc::Service>()?;

    let action_run_sub = topics::behave::state::subscribe(&node)?;
    info!("subscribed to {}", topics::behave::state::NAME);

    info!("ready -- connect Foxglove to ws://localhost:8765");

    // ── Main loop: poll iceoryx2, forward to Foxglove ─────────
    while node.wait(Duration::from_millis(50)).is_ok() {
        while let Some(sample) = action_run_sub.receive()? {
            let bytes = &sample.data[..sample.len as usize];
            channel.log(bytes);
        }
    }

    let _ = server.stop();
    warn!("node loop exited");
    Ok(())
}
