//! Foxglove bridge node -- bidirectional bridge between iceoryx2 and Foxglove.
//!
//! Reads:  `behave/ActionRun`     iceoryx2 -> Foxglove  (tree state)
//! Writes: `behave/ActionRequest` Foxglove -> iceoryx2  (mission commands)
//!
//! The protobuf FileDescriptorSet is embedded at compile time so Foxglove
//! can decode and compose protobuf messages natively.

use std::collections::HashSet;
use std::sync::mpsc;
use std::sync::Arc;
use std::time::Duration;

use anyhow::Result;
use iceoryx2::prelude::*;
use log::{info, warn};
use prost::Message;
use prost_reflect::{DescriptorPool, DynamicMessage, FieldDescriptor, Kind, MessageDescriptor};
use serde_json::{json, Value};

use foxglove::websocket::{Capability, Client, ClientChannel, ServerListener};

use behave::topics;

/// Protobuf FileDescriptorSet generated by prost-build from action.proto.
/// Contains all message types (ActionRun, ActionArgs, etc.).
const ACTION_DESCRIPTOR: &[u8] =
    include_bytes!(concat!(env!("OUT_DIR"), "/action_descriptor.bin"));

// ── JSON Schema generation from protobuf descriptors ────────────

/// Generate a JSON Schema from a protobuf MessageDescriptor.
/// Foxglove does NOT support `$ref`, so all types are inlined.
/// Self-referencing types (e.g. ActionArgs.children) use a generic
/// object schema to break the cycle.
fn proto_to_jsonschema(desc: &MessageDescriptor) -> Vec<u8> {
    let schema = message_schema(desc, &mut HashSet::new());
    serde_json::to_vec(&schema).unwrap()
}

fn message_schema(desc: &MessageDescriptor, visiting: &mut HashSet<String>) -> Value {
    let full_name = desc.full_name().to_string();
    visiting.insert(full_name.clone());

    let mut properties = serde_json::Map::new();
    for field in desc.fields() {
        let field_schema = field_type_schema(&field, visiting);
        let schema = if field.is_list() {
            json!({ "type": "array", "items": field_schema })
        } else if field.is_map() {
            json!({ "type": "object", "additionalProperties": field_schema })
        } else {
            field_schema
        };
        properties.insert(field.json_name().to_string(), schema);
    }

    visiting.remove(&full_name);
    json!({ "type": "object", "properties": properties })
}

fn field_type_schema(field: &FieldDescriptor, visiting: &mut HashSet<String>) -> Value {
    match field.kind() {
        Kind::Double | Kind::Float => json!({ "type": "number" }),
        Kind::Int32 | Kind::Int64 | Kind::Uint32 | Kind::Uint64
        | Kind::Sint32 | Kind::Sint64 | Kind::Fixed32 | Kind::Fixed64
        | Kind::Sfixed32 | Kind::Sfixed64 => json!({ "type": "number" }),
        Kind::Bool => json!({ "type": "boolean" }),
        Kind::String => json!({ "type": "string" }),
        Kind::Bytes => json!({ "type": "string" }),
        Kind::Enum(e) => {
            let values: Vec<String> = e.values().map(|v| v.name().to_string()).collect();
            json!({ "type": "string", "enum": values })
        }
        Kind::Message(m) => {
            if visiting.contains(m.full_name()) {
                // Break self-reference cycle with a generic object.
                json!({ "type": "object" })
            } else {
                message_schema(&m, visiting)
            }
        }
    }
}

// ── Foxglove listener ───────────────────────────────────────────

/// Listener that forwards Foxglove Publish panel messages to iceoryx2.
/// Accepts both JSON and protobuf encodings; JSON is converted to protobuf
/// using the embedded FileDescriptorSet.
struct BridgeListener {
    request_tx: mpsc::Sender<Vec<u8>>,
    descriptor_pool: DescriptorPool,
}

impl BridgeListener {
    fn json_to_protobuf(&self, schema_name: &str, json: &[u8]) -> Result<Vec<u8>> {
        let desc = self
            .descriptor_pool
            .get_message_by_name(schema_name)
            .ok_or_else(|| anyhow::anyhow!("unknown schema: {schema_name}"))?;
        let mut deserializer = serde_json::Deserializer::from_slice(json);
        let msg = DynamicMessage::deserialize(desc, &mut deserializer)?;
        Ok(msg.encode_to_vec())
    }
}

impl ServerListener for BridgeListener {
    fn on_message_data(
        &self,
        _client: Client,
        channel: &ClientChannel,
        payload: &[u8],
    ) {
        let proto_bytes = match channel.encoding.as_str() {
            "protobuf" => payload.to_vec(),
            "json" => match self.json_to_protobuf(&channel.schema_name, payload) {
                Ok(bytes) => bytes,
                Err(e) => {
                    warn!("failed to convert JSON to protobuf: {e}");
                    return;
                }
            },
            other => {
                warn!("unsupported encoding from Foxglove: {other}");
                return;
            }
        };

        info!(
            "received {} bytes from Foxglove on '{}' ({})",
            proto_bytes.len(),
            channel.topic,
            channel.encoding,
        );
        let _ = self.request_tx.send(proto_bytes);
    }
}

// ── Node entry point ────────────────────────────────────────────

pub fn run() -> Result<()> {
    behave::logging::init("Foxglove");
    info!("starting");

    // ── Descriptor pool for JSON <-> protobuf conversion ──────
    let descriptor_pool = DescriptorPool::decode(ACTION_DESCRIPTOR)
        .map_err(|e| anyhow::anyhow!("failed to decode descriptor set: {e}"))?;

    // ── Channel for Foxglove -> iceoryx2 messages ─────────────
    let (request_tx, request_rx) = mpsc::channel::<Vec<u8>>();

    // ── Foxglove WebSocket server ─────────────────────────────
    let listener = Arc::new(BridgeListener {
        request_tx,
        descriptor_pool: descriptor_pool.clone(),
    });

    let server = foxglove::WebSocketServer::new()
        .name("behave")
        .bind("0.0.0.0", 8765)
        .capabilities([Capability::ClientPublish])
        .supported_encodings(["json", "protobuf"])
        .listener(listener)
        .start_blocking()
        .map_err(|e| anyhow::anyhow!("failed to start foxglove server: {e}"))?;
    info!("WebSocket server listening on 0.0.0.0:8765");

    // ── Foxglove channels ───────────────────────────────────────

    // ActionRun: server -> client (protobuf for Raw Messages panel)
    let action_run_schema = foxglove::Schema::new(
        "behave.actions.ActionRun",
        "protobuf",
        ACTION_DESCRIPTOR,
    );
    let action_run_channel = foxglove::ChannelBuilder::new("/behave/ActionRun")
        .message_encoding("protobuf")
        .schema(action_run_schema)
        .build_raw()
        .map_err(|e| anyhow::anyhow!("failed to create ActionRun channel: {e}"))?;
    info!("channel /behave/ActionRun ready");

    // ActionRequest: json + jsonschema for the Publish panel.
    let action_args_desc = descriptor_pool
        .get_message_by_name("behave.actions.ActionArgs")
        .ok_or_else(|| anyhow::anyhow!("ActionArgs not found in descriptor pool"))?;
    let action_args_jsonschema = proto_to_jsonschema(&action_args_desc);

    let action_args_schema = foxglove::Schema::new(
        "behave.actions.ActionArgs",
        "jsonschema",
        action_args_jsonschema,
    );
    let _action_request_channel = foxglove::ChannelBuilder::new("/behave/ActionRequest")
        .message_encoding("json")
        .schema(action_args_schema)
        .build_raw()
        .map_err(|e| anyhow::anyhow!("failed to create ActionRequest channel: {e}"))?;
    info!("channel /behave/ActionRequest ready");

    // ── iceoryx2 node ─────────────────────────────────────────
    let node = NodeBuilder::new().create::<iceoryx2::prelude::ipc::Service>()?;

    let action_run_sub = topics::behave::state::subscribe(&node)?;
    info!("subscribed to {}", topics::behave::state::NAME);

    let request_pub = topics::behave::request::publish(&node)?;
    info!("publishing {}", topics::behave::request::NAME);

    info!("ready -- connect Foxglove to ws://localhost:8765");

    // ── Main loop ─────────────────────────────────────────────
    while node.wait(Duration::from_millis(50)).is_ok() {
        // iceoryx2 -> Foxglove (ActionRun state)
        while let Some(sample) = action_run_sub.receive()? {
            let bytes = &sample.data[..sample.len as usize];
            action_run_channel.log(bytes);
        }

        // Foxglove -> iceoryx2 (ActionRequest commands)
        while let Ok(bytes) = request_rx.try_recv() {
            info!("forwarding {} bytes to {}", bytes.len(), topics::behave::request::NAME);
            if let Err(e) = topics::publish_bytes(&request_pub, &bytes) {
                warn!("failed to forward action request: {e}");
            }
        }
    }

    let _ = server.stop();
    warn!("node loop exited");
    Ok(())
}
