// @generated by protoc-gen-es v2.2.3 with parameter "json_types=true"
// @generated from file behave/core/behavior/v1/behavior.proto (package behavior.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";

/**
 * Describes the file behave/core/behavior/v1/behavior.proto.
 */
export const file_behave_core_behavior_v1_behavior = /*@__PURE__*/
  fileDesc("CiZiZWhhdmUvY29yZS9iZWhhdmlvci92MS9iZWhhdmlvci5wcm90bxILYmVoYXZpb3IudjEiHwoPU2F5SGVsbG9SZXF1ZXN0EgwKBG5hbWUYASABKAkiIwoQU2F5SGVsbG9SZXNwb25zZRIPCgdtZXNzYWdlGAEgASgJMlwKD0JlaGF2aW9yU2VydmljZRJJCghTYXlIZWxsbxIcLmJlaGF2aW9yLnYxLlNheUhlbGxvUmVxdWVzdBodLmJlaGF2aW9yLnYxLlNheUhlbGxvUmVzcG9uc2UiAEJtCg9jb20uYmVoYXZpb3IudjFCDUJlaGF2aW9yUHJvdG9QAaICA0JYWKoCC0JlaGF2aW9yLlYxygILQmVoYXZpb3JcVjHiAhdCZWhhdmlvclxWMVxHUEJNZXRhZGF0YeoCDEJlaGF2aW9yOjpWMWIGcHJvdG8z");

/**
 * Describes the message behavior.v1.SayHelloRequest.
 * Use `create(SayHelloRequestSchema)` to create a new message.
 */
export const SayHelloRequestSchema = /*@__PURE__*/
  messageDesc(file_behave_core_behavior_v1_behavior, 0);

/**
 * Describes the message behavior.v1.SayHelloResponse.
 * Use `create(SayHelloResponseSchema)` to create a new message.
 */
export const SayHelloResponseSchema = /*@__PURE__*/
  messageDesc(file_behave_core_behavior_v1_behavior, 1);

/**
 * The service definition
 *
 * @generated from service behavior.v1.BehaviorService
 */
export const BehaviorService = /*@__PURE__*/
  serviceDesc(file_behave_core_behavior_v1_behavior, 0);

