// @generated by protoc-gen-connect-es v1.6.1
// @generated from file behave/core/behavior/v1/behavior.proto (package behavior.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { SayHelloRequest, SayHelloResponse } from "./behavior_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * The service definition
 *
 * @generated from service behavior.v1.BehaviorService
 */
export const BehaviorService = {
  typeName: "behavior.v1.BehaviorService",
  methods: {
    /**
     * A simple RPC
     *
     * @generated from rpc behavior.v1.BehaviorService.SayHello
     */
    sayHello: {
      name: "SayHello",
      I: SayHelloRequest,
      O: SayHelloResponse,
      kind: MethodKind.Unary,
    },
  }
};

